default: &default  
  pool: 5
  timeout: 5000

  adapter: postgresql
  host: localhost
  encoding: unicode
  username: matiasaraya
  password: 1234

development:  
  <<: *default
  database: rt-bot_dev

test:  
  <<: *default
  database: rt-bot_test

production:  
  <<: *default
  database: rt-bot_prod
